server:
  port: 8082

service:
  limit: 10000

spring:
  application:
    name: limit
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /h2

