CREATE TABLE products (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    account varchar(255) NOT NULL,
    balance float8 NOT NULL,
    "type" int4 NOT NULL,
    userid int8 NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

insert into products (account, balance, "type", userid)
values ('100001', 0,     1, 1),
       ('100002', -0.1,  2, 1),
       ('100003', 10.49, 2, 2),
       ('100004', 90.99, 1, 2);